security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: 
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        #invalidate:
            #pattern:    ^/oauth/v2/token/invalidate
            #stateless:  true
            #anonymous:  false 

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            stateless:  true
            anonymous:  true
            fos_oauth:  true

    access_control:
        - { path: ^/api/v1/users$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] , methods: [POST]}
        - { path: ^/api/v1/files$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] , methods: [POST]}
        - { path: ^/api/v1/users/forgotpassword$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] , methods: [PUT]}
        - { path: ^/api/v1/users/changepassword$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] , methods: [PATCH]}
        - { path: ^/api/v1/rateLimit/remove$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] , methods: [POST]}
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
